### ISSUE TITLE
Backend is unavailable

### ISSUE THREAD

**Issue by abelic** [WebDB-App/app#33]
After starting  app with 
docker pull webdb/app && \
docker rm -f $(docker ps -a -q --filter ancestor=webdb/app) webdb || echo && \
docker run --name webdb -d \
	--restart=always \
	--add-host="host.docker.internal:host-gateway" \
	-v $HOME/.webdb:/usr/src/app/static/version \
	-p 127.0.0.1:22071:22071 webdb/app
	
and adding server I'm getting message : 
Backend is unavailable

**Comment by WebDB-App** [comment]
Hello,

Can you give me the tail of `docker logs -n 20 webdb` please

**Comment by nashihunamien** [comment]
Hello in my case it happened after adding new mysql connection.
Trying to clean the environment and rerun the docker compose still same, tested using incognito also having same output.

```
webdb          | 22071             database WebDB App running
webdb          |  3306                      show global variables
webdb          | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
webdb          | TypeError: this.connection.promise is not a function
webdb          |     at MySQL.runCommand (file:///usr/src/app/src/wrapper/mysql.js:382:44)
webdb          |     at MySQL.variableList (file:///usr/src/app/src/wrapper/mysql.js:170:27)
webdb          |     at MySQL.getVersionInfo (file:///usr/src/app/src/wrapper/mysql.js:427:31)
webdb          |     at Wrapper.getDriver (file:///usr/src/app/src/shared/wrapper.js:73:40)
webdb          |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webdb          |     at async Controller.getStructure (file:///usr/src/app/src/endpoint/server/controller.js:36:18)
webdb          | TypeError: this.connection.promise is not a function
webdb          |     at MySQL.runCommand (file:///usr/src/app/src/wrapper/mysql.js:382:44)
webdb          |     at MySQL.variableList (file:///usr/src/app/src/wrapper/mysql.js:170:27)
webdb          |     at MySQL.getVersionInfo (file:///usr/src/app/src/wrapper/mysql.js:427:31)
webdb          |     at Wrapper.getDriver (file:///usr/src/app/src/shared/wrapper.js:73:40)
webdb          |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webdb          |     at async Controller.getStructure (file:///usr/src/app/src/endpoint/server/controller.js:36:18)
webdb          | Exiting WebDB
```

**Comment by aleluff** [comment]
Can you tell me if thé user you use yo connect to the dB has the right to run `show global variables`

**Comment by aleluff** [comment]
I've just increase logging, can you re-run `docker pull webdb/app &&
docker rm -f $(docker ps -a -q --filter ancestor=webdb/app) webdb || echo &&
docker run --name webdb -d
--restart=always
--add-host="host.docker.internal:host-gateway"
-v $HOME/.webdb:/usr/src/app/static/version
-p 127.0.0.1:22071:22071 webdb/app` and tell me the error you get please

**Comment by WebDB-App** [comment]
@abelic Any up ?

**Comment by 86jkuncle** [comment]
@WebDB-App  i have same problem, docker logs -n 20 webdb 
```
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7f250da4c24a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7f250da4c305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]

  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7fdd97d9624a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fdd97d96305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]
```

**Comment by aleluff** [comment]
Hello,

Can you give me more lines of logs please

Replace the 20 with 150

**Comment by 86jkuncle** [comment]
@aleluff  docker logs -n 150 webdb
```
  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7f80618c124a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7f80618c1305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]

  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7f25ad56324a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7f25ad563305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]

  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7fc8941df24a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fc8941df305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]

  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7fdf0c44624a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fdf0c446305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]

  #  node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
 2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
 3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf1a8ce  [node]
 5: 0xf1bd8c node::Start(int, char**) [node]
 6: 0x7f02d712324a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7f02d7123305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe5b47e _start [node]
```

**Comment by 86jkuncle** [comment]
os version:  centos7.9 2009
core:  3.10.0-1160.el7.x86_64
docker version: Docker version 20.10.9, build c2ea9bc

**Comment by aleluff** [comment]
Sorry, but can you again increase to 500 lines please

*Alexandre Biche*
