### ISSUE TITLE
Backend is unavailable : MySQL ?

### ISSUE THREAD

**Issue by Kouromo** [WebDB-App/app#38]
Here are the logs.

```
webdb-1  | 22071             database WebDB App running
webdb-1  |  3307                      show global variables
webdb-1  | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
webdb-1  | TypeError: this.connection.promise is not a function
webdb-1  |     at MySQL.runCommand (file:///usr/src/app/src/wrapper/mysql.js:382:44)
webdb-1  |     at MySQL.variableList (file:///usr/src/app/src/wrapper/mysql.js:170:27)
webdb-1  |     at MySQL.getVersionInfo (file:///usr/src/app/src/wrapper/mysql.js:427:31)
webdb-1  |     at Wrapper.getDriver (file:///usr/src/app/src/shared/wrapper.js:73:40)
webdb-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webdb-1  |     at async Controller.getStructure (file:///usr/src/app/src/endpoint/server/controller.js:36:18)
webdb-1  | TypeError: this.connection.promise is not a function
webdb-1  |     at MySQL.runCommand (file:///usr/src/app/src/wrapper/mysql.js:382:44)
webdb-1  |     at MySQL.variableList (file:///usr/src/app/src/wrapper/mysql.js:170:27)
webdb-1  |     at MySQL.getVersionInfo (file:///usr/src/app/src/wrapper/mysql.js:427:31)
webdb-1  |     at Wrapper.getDriver (file:///usr/src/app/src/shared/wrapper.js:73:40)
webdb-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webdb-1  |     at async Controller.getStructure (file:///usr/src/app/src/endpoint/server/controller.js:36:18)
webdb-1  | Exiting WebDB
webdb-1 exited with code 0
```

**Comment by aleluff** [comment]
Can you tell me if the user you use yo connect to the dB has the right to run show global variables

**Comment by aleluff** [comment]
Can you tell me if thé user you use yo connect to the dB has the right to run `show global variables`

**Comment by Kouromo** [comment]
The user used in the MySQL database is allowed to use "show global variables". I've tried deleting the links to the saved databases in"C:\Users\CurrentUser\.webdb" and I still have the issue.

**Comment by Kouromo** [comment]
(I closed the issue by mistake)

**Comment by aleluff** [comment]
I've just increase logging, can you re-run 

```
docker pull webdb/app &&
docker rm -f $(docker ps -a -q --filter ancestor=webdb/app) webdb || echo &&
docker run --name webdb -d
--restart=always
--add-host="host.docker.internal:host-gateway"
-v $HOME/.webdb:/usr/src/app/static/version
-p 127.0.0.1:22071:22071 webdb/app
````

and tell me the error you get please

**Comment by Kouromo** [comment]
I don't really understand why but Webdb is working again after running your query. Thank you.

**Comment by aleluff** [comment]
I've also fix a issue, it surely comes from there
